
const API="http://localhost:8000/api";
const PRODUCTS=[
{id:"arc-core",name:"Arc Core Oversized Tee",price:899,oldPrice:1199,image:"assets/arc-core.jpg",tag:"Drop 001",description:"Power Within.",sizes:["S","M","L","XL","XXL"]},
{id:"multiverse",name:"Multiverse Oversized Tee",price:899,oldPrice:1199,image:"assets/multiverse.jpg",tag:"Drop 001",description:"Different realities. Same purpose.",sizes:["S","M","L","XL","XXL"]},
{id:"hero-code",name:"Hero Code Oversized Tee",price:899,oldPrice:1199,image:"assets/hero-code.jpg",tag:"Drop 001",description:"Code. Discipline. Focus. Purpose.",sizes:["S","M","L","XL","XXL"]}
];
const cart=()=>JSON.parse(localStorage.getItem("satyx_cart")||"[]");
function save(c){localStorage.setItem("satyx_cart",JSON.stringify(c));count()}
function count(){document.querySelectorAll("[data-count]").forEach(e=>e.textContent=cart().reduce((n,x)=>n+x.qty,0))}
function toast(t){let e=document.querySelector(".toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function add(id,size="M"){let c=cart(),x=c.find(i=>i.id===id&&i.size===size);x?x.qty++:c.push({id,size,qty:1});save(c);toast("Added to cart")}
function renderCards(){document.querySelectorAll("#products").forEach(e=>e.innerHTML=PRODUCTS.map(p=>`<article class="card"><a href="product.html?id=${p.id}"><div class="pic"><img src="${p.image}" alt="${p.name}"></div></a><div class="info"><h3>${p.name}</h3><div class="meta"><span>${p.tag}</span><span class="price">₹${p.price}<span class="old">₹${p.oldPrice}</span></span></div><a class="btn red" href="product.html?id=${p.id}">View product</a></div></article>`).join(""))}
function renderProduct(){let e=document.querySelector("#product");if(!e)return;let p=PRODUCTS.find(x=>x.id===new URLSearchParams(location.search).get("id"))||PRODUCTS[0];e.innerHTML=`<div class="box"><img class="lookbook" src="${p.image}" alt="${p.name}"></div><div class="box"><div class="eyebrow">${p.tag}</div><h1>${p.name}</h1><p class="sub">${p.description}</p><h2>₹${p.price}</h2><div id="sizes">${p.sizes.map((s,i)=>`<button class="btn ${i===1?"red":"dark"}" onclick="window.sel='${s}';document.querySelectorAll('#sizes .btn').forEach(x=>x.classList.remove('red'));this.classList.add('red')">${s}</button>`).join(" ")}</div><div class="buttons"><button class="btn red" onclick="add('${p.id}',window.sel||'M')">Add to cart</button><a class="btn dark" href="cart.html">Cart</a></div></div>`}
function renderCart(){let e=document.querySelector("#cart");if(!e)return;let c=cart();if(!c.length){e.innerHTML='<div class="box"><h2>Your cart is empty.</h2><a class="btn red" href="shop.html">Shop Drop 001</a></div>';return}let sub=0;let rows=c.map(i=>{let p=PRODUCTS.find(x=>x.id===i.id);sub+=p.price*i.qty;return `<div class="cart-row"><img src="${p.image}"><div><b>${p.name}</b><p class="sub">Size ${i.size} · Qty ${i.qty}</p><button class="btn dark" onclick="removeItem('${i.id}','${i.size}')">Remove</button></div><b>₹${p.price*i.qty}</b></div>`}).join("");let ship=sub>=1499?0:79;e.innerHTML=`<div>${rows}</div><aside class="summary"><h3>Summary</h3><div class="summary-row"><span>Subtotal</span><b>₹${sub}</b></div><div class="summary-row"><span>Shipping</span><b>${ship?"₹79":"FREE"}</b></div><div class="summary-row total"><span>Total</span><b>₹${sub+ship}</b></div><a class="btn red" href="checkout.html">Checkout</a></aside>`}
function removeItem(id,size){save(cart().filter(x=>!(x.id===id&&x.size===size)));renderCart()}
async function auth(form,type){let data=Object.fromEntries(new FormData(form));try{let r=await fetch(`${API}/auth/${type}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),j=await r.json();if(!r.ok)throw Error(j.detail||"Request failed");localStorage.satyx_token=j.token;toast("Welcome to SATYX");setTimeout(()=>location.href="index.html",500)}catch(e){toast(e.message)}}
document.addEventListener("DOMContentLoaded",()=>{count();renderCards();renderProduct();renderCart();document.querySelector("#login")?.addEventListener("submit",e=>{e.preventDefault();auth(e.target,"login")});document.querySelector("#register")?.addEventListener("submit",e=>{e.preventDefault();auth(e.target,"register")})});
